### ISSUE TITLE
How are the equations in the paper expressed in the code?

### ISSUE THREAD

**Issue by jeremytanjianle** [dwadden/dygiepp#107]
Hi, 

Loving the work. Am still using this for years.
Can I ask where is the propagation for events expressed in the code? (specifically, the equations (2,3,4) in appendix B of the paper)

Firstly, is it correct to say that this formula happens in [`_compute_argument_scores`](https://github.com/dwadden/dygiepp/blob/a8360fef924c6e2adaf4831701f83a36bca1dc7f/dygie/models/events.py#L294)?
I'm confused because in the code V seems to be the output of `_compute_argument_scores` whereas in the paper it is the input.
![image](https://user-images.githubusercontent.com/28703546/209777925-523942e7-9459-4f65-a45e-45a6963ca542.png)

Secondly, where does equation (3) and (4) take place in the code?
I may have missed it, but I can't find the gating functions.
![image](https://user-images.githubusercontent.com/28703546/209778196-f9d5891c-05b5-44de-951e-d20007dae3d1.png)
![image](https://user-images.githubusercontent.com/28703546/209778212-c2b79f62-8f8d-4996-a973-693fe5866ac6.png)

Thanks very much.

**Comment by dwadden** [comment]
Hi,

I'm glad the code has been helpful!

I'm looking through the code now and it looks like coreference propagation is implemented [here](https://github.com/dwadden/dygiepp/blob/a8360fef924c6e2adaf4831701f83a36bca1dc7f/dygie/models/dygie.py#L231), but relation propagation and event propagation aren't implemented in the "release" version of the code.

The reason was that, in the paper, we found that relation and event prop didn't really help, so we decided to simplify the code and get rid of these options. But event prop is available on the [emnlp-2019 branch](https://github.com/dwadden/dygiepp/blob/emnlp-2019/dygie/models/events.py#L250). Let me know if you've got questions about this.
