### ISSUE TITLE
ACE05 data preprocess problem: get_token_of

### ISSUE THREAD

**Issue by LarryLee-BD** [dwadden/dygiepp#15]
Hi, when I ran the preprocessing script parse_ace_event.py, I got the _Exception: Should not get here_ from the get_token_of function. I found that it was the char index couldn't match the token index which may due to the tokenization.  Have you ever met such problem, and how should i fix the problem?

**Comment by rockman1989** [comment]
Hi, when I run "pip install -r requirements.txt" , got an error, "ERROR: Failed building wheel for jsonnet".  Do you have met this problem?

**Comment by dwadden** [comment]
@LarryLee-BD the problem is probably caused by the version of Spacy being used. The Spacy tokenizer and sentencizer change between version, and newer versions don't always have the correct behavior. Can you confirm that you're using the exact setup specified here https://github.com/dwadden/dygiepp#ace05-event? Let me know if you still get the same error after checking this.

**Comment by dwadden** [comment]
@rockman1989 I address this in your other issue https://github.com/dwadden/dygiepp/issues/16.

**Comment by dwadden** [comment]
I'm going to close these. Feel free to re-open if this is still an issue.
