### ISSUE TITLE
some questions about the codes in

### ISSUE THREAD

**Issue by HUSTHY** [dwadden/dygiepp#2]

**Comment by HUSTHY** [comment]
I do not understand how to use DyGIE(Model) or where init the model in the project. I want to know how to get the span representations about the sentence. so there are some questions:
1、code in def __init__() function
`self._endpoint_span_extractor = EndpointSpanExtractor(context_layer.get_output_dim(),
                                                              combination="x,y",
                                                              num_width_embeddings=max_span_width,
                                                              span_width_embedding_dim=feature_size,
                                                              bucket_widths=False)`
is context_layer.get_output_dim() a certain value？ such as 512 or 768 or others.
2、code in def forward() function
`endpoint_span_embeddings = self._endpoint_span_extractor(contextualized_embeddings, spans)`
is contextualized_embeddings come from bert mode outputs an tensor with shape (768,)?
and is the spans just come from function enumerate_spans(sentence)?

**Comment by dwadden** [comment]
Thanks for the question. I will have the code cleaned up by the end of the month with a usable README and instructions on how to run the models.

In the meantime: we're using the AllenNLP framework, which relies on config files to specify the dimensionality of things like `context_layer`. The config files are stored in https://github.com/dwadden/dygiepp/tree/master/training_config. Within that folder, there are `jsonnet` files like https://github.com/dwadden/dygiepp/blob/master/training_config/ace05_best_ner_bert.jsonnet, where the user can specify whether you want to use BERT, how many hidden layers you want, etc.
 
Then there are `libsonnet` files like https://github.com/dwadden/dygiepp/blob/master/training_config/template_dw.libsonnet, which take the `jsonnet` config as input and do the arithmetic of figuring out what the size the `context_layer` should be, based on the flags set by the user in the `jsonnet` file. If `use_bert` is chosen, then the dimensionality is set to 768. If `user_bert_large` is chosen, the dimensionality is set to 1024.

This is confusing and will be fixed by the end of the month, thanks for your patience. Let me know if this doesn't make sense.

**Comment by dwadden** [comment]
OK - the code runs now. If you follow the README, you should be able to get it to run. Let me know if it doesn't.
