### ISSUE TITLE
Training with `ace05_best_ner_bert.jsonnet` returns error: `str' object has no attribute 'get_lr'`

### ISSUE THREAD

**Issue by ndobb** [dwadden/dygiepp#26]
Using the following code:
```python
import json
import sys

from allennlp.commands import main

overrides = json.dumps({"trainer": {"cuda_device": -1}})
runs = [
    ( "../ace05_best_relation_bert.jsonnet", "../data/relation" )
]

for config_file, serialization_dir in runs:

    sys.argv = [
        "allennlp",  
        "train",
        config_file,
        "-s", serialization_dir,
        "--include-package", "dygie",
        "--include-package", "ie_json",
        "-o", overrides,
    ]

    main()
```

Attempting to run `ace05_best_ner_bert.jsonnet` returns the error:
![image](https://user-images.githubusercontent.com/10424962/87597779-3dfc3b80-c6a7-11ea-8b27-1682bddd2a1c.png)

I'm using the versions of `allennlp` and `torch` suggested in requirements.txt:
![image](https://user-images.githubusercontent.com/10424962/87612426-61cb7b80-c6bf-11ea-8bf6-f45ca783be0c.png)
![image](https://user-images.githubusercontent.com/10424962/87612444-6b54e380-c6bf-11ea-838e-b86c61e20441.png)

**Comment by dwadden** [comment]
I tried running your script from the root of the `dygiepp` code repo and got 
```
  File "scratch/scratch2.py", line 23, in <module>
    main()
  File "/data/dwadden/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 101, in main
    import_submodules(package_name)
  File "/data/dwadden/anaconda3/envs/dygiepp/lib/python3.7/site-packages/allennlp/common/util.py", line 323, in import_submodules
    module = importlib.import_module(package_name)
  File "/data/dwadden/anaconda3/envs/dygiepp/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ie_json'
```
Can you tell me what directory you ran this script from, and any additional dependencies? 
It might be that something weird is happening as a result of running AllenNLP as a Python library, instead of calling at the command line. I'm not sure.

If you're doing relation extraction over scientific text, your best starting place is probably the [SciERC training script](https://github.com/dwadden/dygiepp/blob/master/scripts/train/train_scierc_lightweight.sh). Can you modify the data paths in that script and get things to run?

If you still run into problems, feel free to share the data / code needed to fully reproduce the bug and I can try to help.

**Comment by ndobb** [comment]
Thanks for your help @dwadden . I'm guessing this is some issue on my end, as I've changed the config a bit. I'll close for now and reopen later if I can provide better information.

**Comment by GillesJ** [comment]
@ndobb I see that you are using the same strategy as me for calling training for use with an interactive debugger.
I have a tangentially related question: how did you pass the training - dev - test file path arguments?
I used `os.environ` to set environment variables, since the jsonnet + libsonnet template calls `std.extVar("ie_train_data_path")`.

Here's how I made it work, but I am curious at how to edit the jsonnet or libsonnet template as I don't know the format prefered by AllenNLP:
```
#!/usr/bin/env python3
'''
Calling AllenNLP train script in Python for interactive debugging.
train_ace05_event.py in dygiepp
'''
import shutil
import sys
from pathlib import Path
import os
from allennlp.commands import main

base_dir = Path("~/repos/dygiepp")
config_file = str(base_dir / "training_config/ace05_event.jsonnet")
experiment_name = "ace05-event"
data_root = base_dir / "data/ace-event/processed-data/default-settings/json"
serialization_dir = str(base_dir / "/tmp/debugger_train")

# Use env vars for libsonnet template compatibility.
os.environ["cuda_device"] = str(0)
os.environ["ie_train_data_path"] = str(data_root / "train.json")
os.environ["ie_dev_data_path"] = str(data_root / "dev.json")
os.environ["ie_test_data_path"] = str(data_root / "test.json")

# Training will fail if the serialization directory already
# has stuff in it. If you are running the same training loop
# over and over again for debugging purposes, it will.
# Hence we wipe it out in advance.
# BE VERY CAREFUL NOT TO DO THIS FOR ACTUAL TRAINING!
shutil.rmtree(serialization_dir, ignore_errors=True)

# Assemble the command into sys.argv
sys.argv = [
    "allennlp",  # command name, not used by main
    "train",
    config_file,
    "--cache-directory", str(data_root / "cached"),
    "--serialization-dir", serialization_dir,
    "--include-package", "dygie",
]
main()
```

**Comment by dwadden** [comment]
The data paths get set here: https://github.com/dwadden/dygiepp/blob/master/training_config/template_dw.libsonnet#L249.

You can always just edit these lines in the template to point at your data. In the new version of the code, these files will always be set in the `jsonnet` config, which will hopefully be less confusing.
