### ISSUE TITLE
using dygiepp for other languages than english

### ISSUE THREAD

**Issue by desothier1** [dwadden/dygiepp#55]
Hi,

I would use dygiepp on the dutch language.
It means I should use other embeddings than Bert.  There is a Dutch version 'Bertje'.
I would be grateful if you could give me a clue where to start to adapt in your script, or in allennlp to use this Dutch version.

Thanks a lot

**Comment by GillesJ** [comment]
You can use any model compatible with the huggingface/transformers library as this lib is used by AllenNLP to handle transformer-based models:

- For autodownload: If you have a huggingface/transformers you can simply edit `bert_model` key and embedding size keys, max seq length of the train config file with the model identifier and corresponding embedding size values from the huggingface model zoo (https://huggingface.co/wietsedv/bert-base-dutch-cased). This will autodownload from the huggingface model zoo.
- Local weights and tokenizer: Instead of the huggingface model identifier pass the path to the model dir with the pytorch_model.bin, config.json and vocab.txt.

**Comment by dwadden** [comment]
Thanks Gilles! @desothier1 if you'd like an example, see here: https://github.com/dwadden/dygiepp/blob/master/training_config/chemprot.jsonnet#L4. You can just swap in the huggingface ID of the BERT model you want to use, and you should be all set.

**Comment by desothier1** [comment]
Thanks !
