### ISSUE TITLE
Hi, nice work! In event extraction, do you use BERT or Roberta?

### ISSUE THREAD

**Issue by jianliu-ml** [dwadden/dygiepp#67]
It seems that you set "roberta-base" in event.jsonnet

**Comment by YeDeming** [comment]
And the shape of word embedding in the downloaded ace-event model is (50265, 768)

**Comment by dwadden** [comment]
You're right, the current `master` branch of the code uses RoBERTa rather than BERT, which is different from the paper. The code's been updated substantially since the paper was released; in particular, the configuration is much easier to deal with now. In particular, if you'd like to train the model using a different BERT, you should be able to change the config. If you'd like to do this but can't figure out how, let me know.

If you need the code as it was for the paper, you can use [this branch](https://github.com/dwadden/dygiepp/tree/emnlp-2019). From the [ACE event config](https://github.com/dwadden/dygiepp/blob/emnlp-2019/training_config/template_dw.libsonnet#L141), it looks like I was using `bert-large-cased`. 

I wouldn't recommend dealing with the older version of the code unless you need to for some reason.
