### ISSUE TITLE
Performance of trigger word classification

### ISSUE THREAD

**Issue by YeDeming** [dwadden/dygiepp#68]
Hi,

In Table 4 & Table 6,  BERT Finetune gets F1 69.7 in trigger word classication. But in Table 9 in the appendix, the averaged F1  is 73.0. Could you please tell me what is the difference between two results?

Best,
Deming

**Comment by dwadden** [comment]
Hi Deming,

I believe that Tables 1 and 9 refer to the test set, while tables 4 and 6 refer to the dev set? Apparently the test set is a bit easier.

Dave

**Comment by YeDeming** [comment]
The caption of Table 6 says "trigger extraction F1 on ACE05-E test set". Table 1 and Table 9 also refer to the test set.

The following works OneIE[https://www.aclweb.org/anthology/2020.acl-main.713/] and [MQAEE](https://www.aclweb.org/anthology/2020.findings-emnlp.73/ ) regard 69+ as the test set result.

So 73.0 is the result of dev set?

**Comment by dwadden** [comment]
Ah you're right. Sorry for the confusion, it's been a couple years since this paper was submitted.

- You're right, all numbers are on the test set; this is explained in the caption to Table 5.
- The numbers in Tables 1 and 9 report the performance of a 4-model ensemble, while the numbers in Tables 4 and 6 report the best single model. This is explained in the caption for Table 1. More details are provided in Appendix E, in the section "Event model ensembling".

The code on master won't replicate this score without some work. If your goal is to exactly replicate the results in the paper, I can try to work with you to do that. Otherwise, that's the reason for the discrepancy. I hope that makes more sense.

**Comment by YeDeming** [comment]
I just want to confirm the test set number. Thanks for your rapid reply!

**Comment by dwadden** [comment]
OK, glad that clears it up!
